{
  "formatVersion": "1.1",
  "component": {
    "group": "io.apimap.client",
    "module": "rest-client",
    "version": "2.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.apimap.api",
          "module": "rest-interface",
          "version": {
            "requires": "2.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "rest-client-2.0.5.jar",
          "url": "rest-client-2.0.5.jar",
          "size": 21524,
          "sha512": "6279a1bda335839424126787af8edb371fb739b3e62b8283f4300f1d5b00c56c0360cbe79317f252c714bb509c980836e0f854688e6fc3395f974362484a2328",
          "sha256": "6007d83996e5ab3d75f70832a296574aca2d3a3bbf2b5727c7f974e00b94cdcc",
          "sha1": "2db574ad7a0fa21050a4da92135cdaa9e67ac26e",
          "md5": "cd82c6b36a268626abd97c36994428a7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.httpcomponents",
          "module": "httpclient",
          "version": {
            "requires": "4.5.13"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "io.apimap.api",
          "module": "rest-interface",
          "version": {
            "requires": "2.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "rest-client-2.0.5.jar",
          "url": "rest-client-2.0.5.jar",
          "size": 21524,
          "sha512": "6279a1bda335839424126787af8edb371fb739b3e62b8283f4300f1d5b00c56c0360cbe79317f252c714bb509c980836e0f854688e6fc3395f974362484a2328",
          "sha256": "6007d83996e5ab3d75f70832a296574aca2d3a3bbf2b5727c7f974e00b94cdcc",
          "sha1": "2db574ad7a0fa21050a4da92135cdaa9e67ac26e",
          "md5": "cd82c6b36a268626abd97c36994428a7"
        }
      ]
    }
  ]
}
