{
  "formatVersion": "1.1",
  "component": {
    "group": "io.apimap.client",
    "module": "rest-client",
    "version": "3.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.httpcomponents.client5",
          "module": "httpclient5",
          "version": {
            "requires": "5.1.3"
          }
        },
        {
          "group": "io.apimap.api",
          "module": "rest-interface",
          "version": {
            "requires": "2.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "rest-client-3.0.1.jar",
          "url": "rest-client-3.0.1.jar",
          "size": 22590,
          "sha512": "5af289c73b7d5a50912f358f2bb149477e096ccb617093f2bea9555866283c6b0b1495910af24a52c52e0c1d9a59b8c911025e154e200aa9a39a41f8979a6b85",
          "sha256": "380b242bdaab0ec5a7b4392e756056da3c155954bdd39fc229ce8f0d507e7ae5",
          "sha1": "3ba06306c3616d770bf4b7db65d42e36ef9b621a",
          "md5": "800f499242191d36d29e697b858c7336"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.13.3"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.apache.httpcomponents.client5",
          "module": "httpclient5",
          "version": {
            "requires": "5.1.3"
          }
        },
        {
          "group": "io.apimap.api",
          "module": "rest-interface",
          "version": {
            "requires": "2.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "rest-client-3.0.1.jar",
          "url": "rest-client-3.0.1.jar",
          "size": 22590,
          "sha512": "5af289c73b7d5a50912f358f2bb149477e096ccb617093f2bea9555866283c6b0b1495910af24a52c52e0c1d9a59b8c911025e154e200aa9a39a41f8979a6b85",
          "sha256": "380b242bdaab0ec5a7b4392e756056da3c155954bdd39fc229ce8f0d507e7ae5",
          "sha1": "3ba06306c3616d770bf4b7db65d42e36ef9b621a",
          "md5": "800f499242191d36d29e697b858c7336"
        }
      ]
    }
  ]
}
