name: Build
on:
  push:
    branches:
      - 'feature/**'
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - uses: s4u/maven-settings-action@v2.3.0
        with:
          servers: |
            [{
              "id": "github-file-interface",
              "username": "${{ secrets.MULTI_PACKAGES_USER }}",
              "password": "${{ secrets.MULTI_PACKAGES_TOKEN }}"
            },
            {
              "id": "github-rest-client",
              "username": "${{ secrets.MULTI_PACKAGES_USER }}",
              "password": "${{ secrets.MULTI_PACKAGES_TOKEN }}"
            }]
      - name: Build
        run: mvn package -Dmaven.test.skip -f pom.xml
